### ISSUE TITLE
Warning on `record?` for cljs 3308

### ISSUE THREAD

**Issue by bhauman** [noprompt/ankha#27]
WARNING: record? already refers to: cljs.core/record? being replaced by: ankha.core/record? at line 29 file:/Users/brucehauman/.m2/repository/ankha/ankha/0.1.4/ankha-0.1.4.jar!/ankha/core.cljs

**Comment by noprompt** [comment]
Thanks for bringing this up. I've seen this before but hadn't gotten around to fixing it. I just decided to kill the function altogether as it was only being used in one place.
